replicaCount: 1

image:
  repository: ghcr.io/open-telemetry/demo
  tag: 1.12.0-frontendproxy
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: opentelemetry-demo

resources:
  limits:
    memory: 50Mi

env:
  OTEL_COLLECTOR_NAME: opentelemetry-demo-otelcol
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
  ENVOY_PORT: "8080"

  FLAGD_HOST: opentelemetry-demo-flagd
  FLAGD_PORT: "8013"
  FLAGD_UI_HOST: opentelemetry-demo-flagd
  FLAGD_UI_PORT: "4000"

  FRONTEND_HOST: opentelemetry-demo-frontend
  FRONTEND_PORT: "8080"

  GRAFANA_SERVICE_HOST: opentelemetry-demo-grafana
  GRAFANA_SERVICE_PORT: "80"

  IMAGE_PROVIDER_HOST: opentelemetry-demo-imageprovider
  IMAGE_PROVIDER_PORT: "8081"

  JAEGER_SERVICE_HOST: opentelemetry-demo-jaeger-query
  JAEGER_SERVICE_PORT: "16686"

  LOCUST_WEB_HOST: opentelemetry-demo-loadgenerator
  LOCUST_WEB_PORT: "8089"

  OTEL_COLLECTOR_PORT_GRPC: "4317"
  OTEL_COLLECTOR_PORT_HTTP: "4318"
